### PR TITLE
2.10.1

### PR DESCRIPTION
**Pull request by macmule**
Added changes from my 2.0.9 fork, 1st attempt at merging

### CODE REVIEW

**Comment by macmule** [comment]
hey.. any plans to merge? :8ball:

**Comment by pmbuko** [comment]
I'm scared. :fearful:

**Comment by macmule** [comment]
Haha. 

Well, can we chat on Slack to discuss??

Regards,

Ben.

**Comment by pmbuko** [comment]
Sounds like a plan. I'm heading to work and will be online soon.

-- Peter (from phone)

**Comment by macmule** [comment]
Closing for now

**Pull request closed without merging**
